version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: gulay06/mybudgetapp-api:latest
    ports:
      - "5162:10000"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=db;Database=MyBudgetApp;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;"
      Jwt__SecretKey: "${JWT_SECRET_KEY}"
      Jwt__Issuer: "${JWT_ISSUER}"
      Jwt__Audience: "${JWT_AUDIENCE}"
    depends_on:
      db:
        condition: service_healthy

  client:
    image: gulay06/mybudgetapp-client:latest
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  sqldata:
