FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MyBudgetApp.Web.csproj", "./"]
RUN dotnet restore "MyBudgetApp.Web.csproj"
COPY . .
RUN dotnet build "MyBudgetApp.Web.csproj" -c Release -o /app/build

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/build .
EXPOSE 10000
ENV ASPNETCORE_URLS=http://+:10000
ENTRYPOINT ["dotnet", "MyBudgetApp.Web.dll"]